### PR TITLE
Inline mode implementation

### PR DESCRIPTION
**Pull request by ihoru**
Here is a simple implementation of bot inline mode.
I've tested this on my own bot. It worked.
If everything is Ok, I will implement tests and docs.
Question: what do you think do we need InlineQueryResult base class with children:  InlineQueryResultArticle,     InlineQueryResultPhoto,     InlineQueryResultGif,     InlineQueryResultMpeg4Gif,     InlineQueryResultVideo?
I think it is not very necessary to create them right now.

Ref TODO: https://github.com/irazasyed/telegram-bot-sdk/issues/95

### CODE REVIEW

**Comment by irazasyed** [comment]
Thanks for the PR. Everything looks good.

Answer to your question: InlineQueryResult base class sounds good.

**Comment by ihoru** [comment]
Ok, I will do it later. But for now this code will be enough for implementing this functionality in my bot ;)

**Comment by jonnywilliamson** [comment]
Hi @ihoru . 

I'm finding it hard to see how this works. Could you explain a little more?

When an inbound UPDATE comes in, for a normal command, it looks like this:

```json
{
    "update_id": 430107013,
    "message": {
        "message_id": 203,
        "from": {
            "id": 9999999,
            "first_name": "Firstname",
            "last_name": "Surname",
            "username": "blahblah"
        },
        "chat": {
            "id": 9999999,
            "first_name": "Firstname",
            "last_name": "Surname",
            "username": "blahblah",
            "type": "private"
        },
        "date": 1456265970,
        "text": "/demo"
    }
}
```

However an inline query update looks like this:

```json
{
    "update_id": 430107012,
    "inline_query": {
        "id": "53443510725146332",
        "from": {
            "id": 9999999,
            "first_name": "Firstname",
            "last_name": "Surname",
            "username": "blahblah"
        },
        "query": "test",
        "offset": ""
    }
}
```

The SDK, tries to process the inbound UPDATE with the `commandshandler` method (in my case I set the webhook to true).

image


The actual `processCommand()` method looks like this:
image


So it only can process a command if there is a `message` branch in the Update object and when THAT has a `text` branch.

Seeing as an inline query doesn't have EITHER of those two, do you use a different method to reply to an inbound inline query object?

Do you just check to see if an inbound update object has an `inline_query` branch and then manually call the `answerInlineQuery` method?

Thanks!

**Comment by ihoru** [comment]
Oh, yep. You are right. There is no implementation for inline quiet in that
class,'cause I don't use it.
I am busy right now. But, hope I can fix that later in a week. Or you can
implement it by yourself and send PR.

**Pull request merged**
