### PR TITLE
Loading file like resource

### PR DESCRIPTION
**Pull request by rkhitin**
Now file can be load like resource. For example:   `$telegram->sendDocument($chatId, fopen($imageUrl));`

### CODE REVIEW

**Comment by jonnywilliamson** [comment]
What benefit does this give us?

Does it allow us to send a file that's not local? Ie 

`$telegram->sendDocument($chatId, fopen('http://example.com/demo.pdf'))`

If so, then +1

**Comment by rkhitin** [comment]
Yes. That was the goal.

**Comment by irazasyed** [comment]
Have you tested this? @rkhitin

**Comment by rkhitin** [comment]
Of course, it's working in real project right now. And, actually, there only two lines was changed.

**Comment by irazasyed** [comment]
Thanks for the PR. Merged. Will tag the update soon.

**Pull request merged**
