### PR TITLE
Fix issue with array to string conversion when trying to use

### PR DESCRIPTION
**Pull request by jonnywilliamson**
forceReply and hide keyboard.

### CODE REVIEW

**Comment by ahmadbadpey** [comment]
when I changes the lines of file  to : 

`return $this->merge(array_merge(['hide_keyboard' => true, 'selective' => false], $params));`

I got this error :  
`$this is not accessible in static context`

**Comment by irazasyed** [comment]
@ahmadbadpey Why would you do that? Please use `dev-develop` branch. Also, create a new issue if you have any issues. Thanks!

**Comment by ahmadbadpey** [comment]
@irazasyed , I tried to upgrade to `dev-develop` mentioned by you, but after that first I got this error : 
```
Cannot use Telegram\Bot\Objects\Message as Message because the name is already in use {"exception":"[object]  
 (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 64): Cannot use Telegram\\Bot\\Objects\\Message as Message because the name is already in use at D:\\wamp\\www\\botshop\\vendor\\irazasyed\\telegram-bot-sdk\\src\\Methods\\Payments.php:5)
```

And then when I removed `use Telegram\Bot\Objects\Message; ` from `payments.php` now I got this error : 

`Declaration of App\Commands\StartCommand::handle($arguments) must be compatible with Telegram\Bot\Commands\Command::handle()`

**Comment by ahmadbadpey** [comment]
No I found that if I use below approach to make a fore_reply button , problem solves : 

```
$forceReply = Keyboard::forceReply(['force_reply' => false]);
$this->replyWithMessage([
		'text'         => 'Please enter your name : ',
		'reply_markup' => $forceReply
]);
```

Before I used this : 

```
$reply_markup = [
		'force_reply' => true
];
$this->replyWithMessage([
		'text'         => 'Please enter your name : ',
		'reply_markup' => $reply_markup 
]);
```

**Pull request merged**
