### PR TITLE
createChatInvitelink returns array and solves the create link issue

### PR DESCRIPTION
**Pull request by arifjawad**
when I call createChatInviteLink it says, return type array given

### CODE REVIEW

**Comment by alies-dev** [comment]
@arifjawad 
Thanks for catching the bug! 

to return `ChatInviteLink` instance, it should be:
```php
return new ChatInviteLink($this->post('createChatInviteLink', $params)->getDecodedBody());
```

**Comment by arifjawad** [comment]
@lptn  Thanks for the update. I tried your given code snippet and it worked perfectly. Thanks

**Comment by raiyan24r** [comment]
I faced the same issue. Thanks @arifjawad for bring this up

**Comment by arifjawad** [comment]
I have updated the PR to return a ChatInviteLink object as per the official docs. Thanks to @lptn

**Comment by irazasyed** [comment]
Thanks

**Comment by phpmac** [comment]
How do I know who enters through which link?

**Pull request merged**
