### PR TITLE
Added new tests and created a Mocking 'Telegram Response' class

### PR DESCRIPTION
**Pull request by jonnywilliamson**
Looking for feedback on this.

Have never done testing before, so I'm sure there can be many improvements or better ways to do things. Please show me how! :)

### CODE REVIEW

**Comment by irazasyed** [comment]
Looks good to me :+1:

**Comment by antoniomadonna** [comment]
Good job :) Moving to a different class seems cleaner.
Maybe, I'd just rename TGMocks to something like MocksProvider, or Mocker, what you think ?
And perhaps it should be inside the Mocks dir ?

**Comment by irazasyed** [comment]
Mocker sounds good :+1:

**Comment by jonnywilliamson** [comment]
@antoniomadonna Yes, I'll move the class. Good idea.

I toyed around with the name for ages, but here's what I thought.

MocksProvider was too long, especially when we will be typing it alot.
Mocker....was there any risk of this being mistook for the Mockery Library?
ResponseGenerator - Too long
Generator - too ambiguous.
APIMock - ??

If everyone thinks Mocker is good I'll change it.

**Pull request merged**
