### PR TITLE
Support forum topics create/edit/close/reopen/delete

### PR DESCRIPTION
**Pull request by makkmarci13**

### CODE REVIEW

**Comment by makkmarci13** [comment]
What I need to do to solve this 2 check?

**Comment by irazasyed** [comment]
Add tests please

**Comment by makkmarci13** [comment]
I made some, these are okey?

**Comment by irazasyed** [comment]
Please fix the tests

**Comment by makkmarci13** [comment]
I think i fixed it

**Comment by irazasyed** [comment]
@makkmarci13 Please run tests in your local env and fix them. Push the final patch!

**Comment by makkmarci13** [comment]
image

For me, now runs.

**Comment by makkmarci13** [comment]
So now what should I do?

**Comment by irazasyed** [comment]
Your tests are invalid. Just remove it for now and I'll merge.

**Comment by irazasyed** [comment]
Thanks

**Comment by sathia-musso** [comment]
Hi, I'd need this file it looks like it's not on the latest version. can it be included please?

**Pull request merged**
