### PR TITLE
setWebhook param is array

### PR DESCRIPTION
**Pull request by autowp**

### CODE REVIEW

**Comment by irazasyed** [comment]
The whole documentation has to be rewritten as per the recent changes that were made and is pending to be tagged.

**Comment by irazasyed** [comment]
I'll have to keep this pending till i release the next version to avoid confusion for people using last tagged version.

**Comment by autowp** [comment]
Ooops. My mistake that is docs from older version

**Comment by irazasyed** [comment]
No probs! Feel free to send PR if you're able to rewrite the docs part for the master branch. Only that thing is pending and holding back the release :)

**Comment by jonnywilliamson** [comment]
https://github.com/jonnywilliamson/telegram-bot-sdk/commit/e408300f11bfd03a6aa47758b195db5a6428d983

**Comment by irazasyed** [comment]
@autowp Closing this PR, Since @jonnywilliamson has sent another PR with the doc changes. The HTML files are actually automatically generated, So we need not edit those. As long as the docs in `docs` directory are updated, we can apply those in HTML too. Thanks though.

**Pull request closed without merging**
