### PR TITLE
Added ability to disable using emojify

### PR DESCRIPTION
**Pull request by ihoru**
I don't use emojies in my project the way you do (with Emojify). That's why I want to be able to disable extra processing of this, not to waste time and memory for it.

If my code satisfies you, I will add ability to set default behavior in config file, and simple test.

### CODE REVIEW

**Comment by ihoru** [comment]
There were added useless commits and merge commit by mistake, sorry.
Please review just last commit, and say if it is Ok, and close the PR. I will fix that issue.

**Comment by irazasyed** [comment]
It's okay. Please do also update it in Laravel config file.

**Comment by jonnywilliamson** [comment]
@irazasyed can squash them all when he merges.

(It makes him happy to do it, so I always give him loads of commits to squash)

**Comment by irazasyed** [comment]
@jonnywilliamson I could but let him update it with laravel config and add simple test.

**Comment by ihoru** [comment]
https://github.com/irazasyed/telegram-bot-sdk/pull/153

**Pull request closed without merging**
