### PR TITLE
Apply fixes from StyleCI

### PR DESCRIPTION
**Pull request by irazasyed**
This pull request applies code style fixes from an analysis carried out by [StyleCI](https://styleci.io).

---

For more information, click [here](https://styleci.io/analyses/qo2P5Q).

### CODE REVIEW

**Comment by irazasyed** [comment]
@jonnywilliamson Code style fixes using the [laravel](https://styleci.readme.io/docs/presets#section-laravel) preset.

**Comment by jonnywilliamson** [comment]
Fantastic!!!

**Comment by jonnywilliamson** [comment]
Can I'm import that in Phpstorm I wonder

**Comment by irazasyed** [comment]
I don't think we can actually import but we can definitely create a new preset in PS with the settings listed on their site.

**Pull request merged**
