### PR TITLE
Dependency Injection in commands constructors

### PR DESCRIPTION
**Pull request by antoniomadonna**
Use Laravel Container Class to resolve commands type hinted dependencies.

### CODE REVIEW

**Comment by jonnywilliamson** [comment]
Just trying to follow this.

You want to use Laravel's IOC container so that you get automatic dependency injection when you create a class for a command?

So that 

```php
<?php

namespace App\Telegram\Bot\commands;

use App\Telegram\Bot\BotCommand;

class start extends BotCommand
{

    protected $demo;
    protected $example;

    public function __construct(Demo $demo, Example $example)
    {
        $this->demo = $demo;
        $this->example = $example;
    }

    protected $name = "start";

    protected $description = "start Description";

    public function handle($arguments)
    {
    }

}
```

Demo and Example are resolved for you automatically?

**Comment by antoniomadonna** [comment]
Yes, exactly.

But I've just discovered that I forgot to check if the constructor is available. I'll fix asap.

**Comment by irazasyed** [comment]
Hey @antoniomadonna 

Thanks for opening a PR. I appreciate your contribution.

I'll test this once you push a fix and merge it if i don't find any issues. Looks good to me. :+1:

**Comment by antoniomadonna** [comment]
ty @irazasyed 

I've fixed the issue :)

**Comment by irazasyed** [comment]
@antoniomadonna Can you please rebase as per the latest changes in master branch?

Also, Please send a separate PR for each change (In this case, Tests should be in a separate PR). You have two different things pushed in one. Please update.

**Comment by antoniomadonna** [comment]
@irazasyed sorry I'm new to contributing, this PR should be ok now, I'm going to submit the tests asap

**Comment by irazasyed** [comment]
@antoniomadonna No problem. Thanks for separating the PRs and for all the contributions :)

**Pull request merged**
