### PR TITLE
Add Emoji Support

### PR DESCRIPTION
**Pull request by filipekiss**
Regarding issue #32, added a Helper class to map keywords to Emoji. 

I used the [simplemap.json](https://github.com/muan/emojilib/blob/master/simplemap.json) as the map since it made more send to me. 
I'm not confident enough on where I should put the JSON map, so I'm open to suggestions. If there's anything you think I need to change, just let me know. :)

Also, I looked for a way to add the `simplemap.json` file as a composer dependency so we wouldn't need to version it and we could just grab from [muan/emojilib](/muan/emojilib) `master` branch. If anyone knows how to do this and think it's worth changing to this approach, let me know.

### CODE REVIEW

**Comment by filipekiss** [comment]
So my editor messed up and my indentation is all wrong. I'll be pushing the changes soon.

**Comment by irazasyed** [comment]
Thanks for the PR. Please fix the issues and commit.

As far as the emoji updates are concerned, We can try submitting a PR to that repo and ask the author to add composer support.

If not that, I found this lib: https://github.com/Ranks/emojione

It has everything we need (And more than we need in fact). Check out the [methods](https://github.com/Ranks/emojione/blob/master/lib/php/src/Client.php). Looks good to me but i hope it doesn't cause any performance issues though.

I'm thinking of just decoupling all these things into an extensions based system, So anyone who want emoji support can add another package as a dependency and enable the extension. Like there's another one here: #103

**Comment by filipekiss** [comment]
Yes, using a separate package as an extension would be better. I'll take a look into [Ranks/emojione](/ranks/emojione) and test to see if I ran into performance issues.

I looked at the Travis CI building and both errors are related to composer issues, nothing to do with changes I made. Not sure how can I fix that.

The @Nitpick-CI changes were already corrected.

**Comment by irazasyed** [comment]
I'll push some changes to this SDK in sometime which would integrate events system (I'll probably use Laravel's Event system maybe), Once that's integrate, you can then listen for various events and build plugins around it to manipulate the data as well as integrate more better with the SDK.

Thanks for your patience and contributions.

**Comment by filipekiss** [comment]
Yeah, an event/hook system would work perfectly for this. Let me know if there's anything I can do to help. :)

**Comment by irazasyed** [comment]
@filipekiss I merged this PR and added emojify to a few other things (New Keyboards) as well as auto translation for updates when retrieving text.

This will be tagged in the upcoming V3 and credited.

Thank you!

**Comment by filipekiss** [comment]
No problem @irazasyed :)

Glad to help!

**Pull request merged**
