### PR TITLE
refactors

### PR DESCRIPTION
**Pull request by imanghafoori1**

### CODE REVIEW

**Comment by irazasyed** [comment]
These were merged previously, isn't it?

**Comment by imanghafoori1** [comment]
Yes, only the 2 latest commits are new. anyway merging this causes no harm, it only adds the new commits to your repo.

**Comment by imanghafoori1** [comment]
I think I have to delete my develop branch after getting merged and recreate it.
I do not know why it is showing the merged commits in this way.

**Comment by irazasyed** [comment]
Just create a new branch and try!

**Comment by imanghafoori1** [comment]
one of the pull requests is coming from a new branch. (develop-artisan) branched of at the latest merged commit. but still shows the entire history.
Any way do not be afraid since you have already done this in the previous merges.
Up until now all of  my PRs on the develop branch were like this one... and it is pilled up.

**Comment by imanghafoori1** [comment]
PR #477 (which is merged ) includes the merged commits of PR #454.

**Pull request closed without merging**
