### PR TITLE
add answerCallbackQuery request method

### PR DESCRIPTION
**Pull request by SamsamBabadi**
added https://core.telegram.org/bots/api#answercallbackquery request for answer CallbackQuery

### CODE REVIEW

**Comment by jonnywilliamson** [comment]
This already exists in the [Api.php](https://github.com/irazasyed/telegram-bot-sdk/blob/master/src/Api.php#L757-L783) file. However it's slightly different:

```php

    public function answerCallbackQuery(array $params)
    {
        return $this->post('answerCallbackQuery', $params);
    }

```

Should this return a TelegramResponse or a new Message object?

I haven't done enough testing on this to decide.

**Comment by irazasyed** [comment]
@SamsamBabadi Thanks for opening a PR.

Like @jonnywilliamson already mentioned, This method is already implemented and looking at the docs, It seems like on success it simply returns a boolean value. Hence, just returning TelegramResponse makes sense than a new Message object -- Perhaps we could return a decoded body too.

**Comment by SamsamBabadi** [comment]
@jonnywilliamson & @irazasyed Thanks for your answers.
I think TelegramResponse is good.
I open this PR because I didn't see this method in last released version. :D
Forever I try to use dev-master version for used this method but none of the methods does not work.

**Comment by irazasyed** [comment]
@SamsamBabadi You'll have to pull `3.*@dev` to get the dev-master version. I'm closing this PR then. Thanks anyway 👍

**Pull request closed without merging**
